---
- name: install TFTPd packages
  apt: pkg={{ item }} state=present
  with_items:
    - xinetd
    - tftpd
    - tftp
    - syslinux-common

- name: write the tftp configuration
  template: src=tftp.j2 dest=/etc/xinetd.d/tftp backup=yes
  notify:
    - restart xinetd

- file: path='{{ tftpboot_dir }}/tftpboot' owner=nobody mode=0777 state=directory
- command: cp /usr/lib/syslinux/pxelinux.0 '{{ tftpboot_dir }}/pxelinux.0' creates='{{ tftpboot_dir }}/pxelinux.0'
- file: path='{{ tftpboot_dir }}/pxelinux.cfg' mode=0777 state=directory
- template: src=default.j2 dest='{{ tftpboot_dir }}/pxelinux.cfg/default' mode=0666

- file: path='{{ tftpboot_dir }}/centos/7/x86_64/' mode=0777 state=directory recurse=yes
- get_url: url='{{ centos_mirror }}isolinux/vmlinuz' dest='{{ tftpboot_dir }}/centos/7/x86_64/vmlinuz'
- get_url: url='{{ centos_mirror }}isolinux/initrd.img' dest='{{ tftpboot_dir }}/centos/7/x86_64/initrd.img'
- get_url: url='{{ centos_mirror }}isolinux/vesamenu.c32' dest='{{ tftpboot_dir }}/vesamenu.c32' mode=0666
- get_url: url='{{ centos_mirror }}isolinux/memtest' dest='{{ tftpboot_dir }}/memtest' mode=0666

- name: ensure xinetd enabled
  service: name=xinetd enabled=yes state=started
