---
- name: enable modules
  template: src=modules.j2 dest=/etc/modules

- name: load module w1-gpio
  modprobe: name=w1-gpio state=present

- name: load module w1-therm
  modprobe: name=w1-therm state=present

- name: clone pi-temperature-logger
  git: repo=https://github.com/dbryant4/pi-temperature-logger.git
       dest=/root/pi-temperature-logger

- name: pi-temperature-logger config
  template: src=local_settings.yml.j2 dest=/root/pi-temperature-logger/local_settings.yml
  notify:
    - add sensors to config

- name: install ntp
  apt: pkg=python-pip state=latest update_cache=yes

- name: install Python packages
  pip: requirements=/root/pi-temperature-logger/requirements.txt

- name: write the rc.local
  template: src=rc.local.j2 dest=/etc/rc.local
