---
- name: install DHCPd packages
  apt: pkg={{ item }} state=present
  with_items:
    - isc-dhcp-server

- set_fact: dnssec_key="{{ansible_local.dnssec.key}}"
  when: ansible_local is defined and ansible_local.dnssec.key is defined

- name: write the dhcpd.conf
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf backup=yes
  notify:
    - restart dhcpd

- name: validate dhcpd.conf
  command: /usr/sbin/dhcpd -t

- name: ensure dhcpd enabled
  service: name=isc-dhcp-server enabled=yes state=started
