---
#https://groups.google.com/forum/#!topic/beagleboard/cDab5xZ-14U
- name: install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - 'build-essential'
    - 'git'
    - 'pkg-config'
    - 'libssl-dev'
    - 'bzip2'
    - 'wget'
    - 'libavahi-client-dev'
    - 'zlib1g-dev'
    - 'libavcodec-dev'
    - 'libavutil-dev'
    - 'libavformat-dev'
    - 'libswscale-dev'



- name: Cloning source
  git: "repo=https://github.com/tvheadend/tvheadend.git dest=/usr/local/src/tvheadend"

- name: Compile tvheadend
  command: ./configure chdir=/usr/local/src/tvheadend 

- name: Compile tvheadend
  command: make chdir=/usr/local/src/tvheadend 

- name: Installing tvheadend
  command: make install chdir=/usr/local/src/tvheadend 
