---
- name: Authorize SSH Key
  authorized_key: user=pi key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: "Generate root SSH Key"
  command: "/usr/bin/ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa creates=/root/.ssh/id_rsa"

- name: install network interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify:
    - restart network

- name: "Install python-apt"
  command: "/usr/bin/apt-get -y install python-apt creates=/usr/share/doc/python-apt"

- name: install ntp
  apt: pkg=ntp state=latest update_cache=yes

- name: write the rc.local
  template: src=rc.local.j2 dest=/etc/rc.local

- name: "set hostname to {{ hostname }}"
  hostname: "name={{ hostname }}"
