---
- name: Authorize SSH Key
  authorized_key: user={{ remote_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: "Generate root SSH Key"
  command: "/usr/bin/ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa creates=/root/.ssh/id_rsa"

- name: install network interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces

- name: Install facter gem
  gem: name=facter state=present

- name: "Setting up apt proxy client"
  template: src=02proxy.j2 dest=/etc/apt/apt.conf.d/02proxy
  when: "apt-cache is defined"

- name: Update apt sources
  command: "/usr/bin/apt-get update"
  when: skip_update == false

- name: "Install python-apt"
  command: "/usr/bin/apt-get -y install python-apt creates=/usr/share/doc/python-apt"

- name: install common packages
  apt: pkg={{ item }} state=present
  with_items:
    - screen
    - vim
    - python-pip

- name: write the rc.local
  template: src=rc.local.j2 dest=/etc/rc.local
  when: skip_rc_local is not defined

- name: installing .screenrc
  template: src=screenrc.j2 dest={{ item }}/.screenrc
  with_items:
    - /home/{{ remote_user }}
    - /root

- name: "set hostname to {{ hostname }}"
  hostname: "name={{ hostname }}"
  when: hostname != False
