---
- name: Authorize SSH Key
  authorized_key: user=pi key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: "Generate root SSH Key"
  command: "/usr/bin/ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa creates=/root/.ssh/id_rsa"

- name: install network interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify:
    - restart network

- name: Install facter gem
  gem: name=facter state=present

- name: Update apt sources
  command: "/usr/bin/apt-get update"

- name: "Install python-apt"
  command: "/usr/bin/apt-get -y install python-apt creates=/usr/share/doc/python-apt"

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - screen
    - vim
    - ntp

- name: write the ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp

- name: write the rc.local
  template: src=rc.local.j2 dest=/etc/rc.local

- name: installing .screenrc
  template: src=screenrc.j2 dest={{ item }}/.screenrc
  with_items:
    - /home/pi
    - /root

- name: "set hostname to {{ hostname }}"
  hostname: "name={{ hostname }}"
