---
- name: install bind packages
  apt: pkg={{ item }} state=present
  with_items:
    - bind9
    - bind9-doc
    - bind9utils
    - dnsutils

- include: gen_dnssec_key.yml
  when: ansible_local is not defined or ansible_local.dnssec.key is not defined
- set_fact: dnssec_key="{{ansible_local.dnssec.key}}"

- template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options backup=yes
  notify:
    - 'restart bind9'

- template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local backup=yes
  notify:
    - 'restart bind9'

- template: src=db.home.j2 dest=/etc/bind/db.home backup=yes validate='/usr/sbin/named-checkzone home %s'
  notify:
    - 'restart bind9'

- template: src=db.home_rev.j2 dest=/etc/bind/db.home_rev backup=yes validate='/usr/sbin/named-checkzone 101.168.192.in-addr.arpa %s'
  notify:
    - 'restart bind9'

- file: path=/etc/bind owner=bind state=directory

- name: 'ensure {{ bind_service_name }} enabled'
  service: 'name={{ bind_service_name }} enabled=yes state=started'
